export default function Head() {
  return (
    <>
      <title>Apex Legends Search User Info</title>
      <meta content='width=device-width, initial-scale=1' name='viewport' />
      <meta name='description' content='Generated by apex legends search user info' />
      <link rel='icon' href='/favicon.ico' />
    </>
  )
}
